# Task 1 :: Data Cleaning Challenge on Sales Data.

In [1]:
import pandas as pd

In [2]:
# Load Sales Data 
sales_2017 = pd.read_csv(r"C:\Users\gthangar\OneDrive - Nokia\1830_Automation\ML\Task\DataAnalysis\Sales Transactions-2017.csv")
sales_2018 = pd.read_csv(r"C:\Users\gthangar\OneDrive - Nokia\1830_Automation\ML\Task\DataAnalysis\Sales Transactions-2018.csv")
sales_2019 = pd.read_csv(r"C:\Users\gthangar\OneDrive - Nokia\1830_Automation\ML\Task\DataAnalysis\Sales Transactions-2019.csv")

In [3]:
# Combine All Yearly Data
sales_data = pd.concat([sales_2017, sales_2018, sales_2019],ignore_index=True)
sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111204,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [6]:
# Check number of rows and columns
sales_data.shape

(111206, 9)

In [4]:
# Check column data types
sales_data.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [5]:
# Check missing values
sales_data.isna().sum()

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

In [7]:
# Check duplicate rows
duplicate_count = sales_data.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 14582

In [9]:
# Remove Duplicate Rows
sales_data.drop_duplicates(inplace=True)
sales_data

C:\Users\gthangar\AppData\Local\Temp\ipykernel_21560\366159422.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_data.drop_duplicates(inplace=True)

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111199,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
111200,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111204,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [10]:
# Remove Completely Empty Rows
sales_data = sales_data.dropna(how="all")
sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111199,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
111200,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111204,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [11]:
# Find rows where Date, Party and Product are all missing
missing_rows = sales_data[sales_data[["Date", "Party", "Product"]].isna().all(axis=1)]
print("Invalid transaction rows:", len(missing_rows))

Invalid transaction rows: 34

In [12]:
# Remove those rows
sales_data = sales_data.drop(index=missing_rows.index)
sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111197,10/10/2019,Sal:4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00",NaN,NaN
111198,10/10/2019,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00",NaN,NaN
111199,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
111200,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN

In [14]:
# Remove Rows with No Transaction Details
missing_rows = sales_data[sales_data[["Date", "Voucher", "Product", "Qty" ,"Rate","Gross","Disc","Voucher Amount"]].isna().all(axis=1)]
print("Rows with no transaction details:", len(missing_rows))
sales_data = sales_data.drop(index=missing_rows.index)
sales_data

Rows with no transaction details: 169

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111197,10/10/2019,Sal:4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00",NaN,NaN
111198,10/10/2019,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00",NaN,NaN
111199,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
111200,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN

In [15]:
# Find rows where Date contains a blank space
empty_spaces = sales_data[sales_data["Date"].astype(str).str.strip() == ""]
print("Rows with blank Date:", len(empty_spaces))

# Remove those rows
sales_data = sales_data.drop(index=empty_spaces.index)
sales_data

Rows with blank Date: 1133

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111197,10/10/2019,Sal:4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00",NaN,NaN
111198,10/10/2019,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00",NaN,NaN
111199,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
111200,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN

In [16]:
# Clean and Convert Date Column
sales_data["Date"] = pd.to_datetime(sales_data["Date"],format="%d/%m/%Y",errors="coerce")
sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,2017-04-01,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,2017-04-01,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,2017-04-01,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,2017-04-01,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111197,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00",NaN,NaN
111198,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00",NaN,NaN
111199,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
111200,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
111201,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN

In [17]:
# Convert Numeric Columns
numeric_columns = ["Qty","Rate", "Gross","Disc","Voucher Amount"]
for column in numeric_columns:
    sales_data[column] = pd.to_numeric(sales_data[column].astype(str).str.replace(",", "", regex=False).str.strip(),errors="coerce")

In [18]:
sales_data.dtypes

Date              datetime64[ns]
Voucher                   object
Party                     object
Product                   object
Qty                      float64
Rate                     float64
Gross                    float64
Disc                     float64
Voucher Amount           float64
dtype: object

In [19]:
sales_data.isna().sum()

Date                  0
Voucher               0
Party                 0
Product               0
Qty                   0
Rate                  1
Gross                 1
Disc              92781
Voucher Amount    70814
dtype: int64

In [20]:
# Handle Missing Discount Values
sales_data["Disc"] = sales_data["Disc"].fillna(0)
sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0,3380.0,0.0,13100.0
1,2017-04-01,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,NaN
2,2017-04-01,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,11500.0,0.0,30990.0
3,2017-04-01,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,NaN
4,2017-04-01,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0,8450.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...
111197,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140.0,26.0,3640.0,0.0,NaN
111198,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600.0,8.4,5040.0,0.0,NaN
111199,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0,5120.0,0.0,NaN
111200,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800.0,8.5,6800.0,0.0,NaN
111201,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0,6400.0,0.0,NaN

In [21]:
# Fill Voucher Amount Within Each Transaction
sales_data["Voucher Amount"] = (sales_data.groupby(["Date", "Voucher", "Party"])["Voucher Amount"].transform("first"))
sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0,3380.0,0.0,13100.0
1,2017-04-01,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,13100.0
2,2017-04-01,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,11500.0,0.0,30990.0
3,2017-04-01,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,30990.0
4,2017-04-01,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0,8450.0,0.0,30990.0
...,...,...,...,...,...,...,...,...,...
111197,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140.0,26.0,3640.0,0.0,34980.0
111198,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600.0,8.4,5040.0,0.0,34980.0
111199,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0,5120.0,0.0,34980.0
111200,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800.0,8.5,6800.0,0.0,34980.0
111201,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0,6400.0,0.0,34980.0

In [23]:
# Remaining missing Voucher Amounts
sales_data["Voucher Amount"] = sales_data["Voucher Amount"].fillna(0)
sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0,3380.0,0.0,13100.0
1,2017-04-01,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,13100.0
2,2017-04-01,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,11500.0,0.0,30990.0
3,2017-04-01,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,30990.0
4,2017-04-01,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0,8450.0,0.0,30990.0
...,...,...,...,...,...,...,...,...,...
111197,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140.0,26.0,3640.0,0.0,34980.0
111198,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600.0,8.4,5040.0,0.0,34980.0
111199,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0,5120.0,0.0,34980.0
111200,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800.0,8.5,6800.0,0.0,34980.0
111201,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0,6400.0,0.0,34980.0

In [24]:
# Check Missing Rate Values
missing_rate = sales_data[sales_data["Rate"].isna()]
print("Missing Rate rows:", len(missing_rate))

Missing Rate rows: 1

In [25]:
# Calculate Missing Rate Values
sales_data.loc[sales_data["Rate"].isna(),"Rate"] = (sales_data["Voucher Amount"] + sales_data["Disc"]) / sales_data["Qty"]
# Calculate Missing Gross Values
sales_data.loc[sales_data["Gross"].isna(),"Gross"] = (sales_data["Qty"] * sales_data["Rate"])

In [26]:
sales_data.isna().sum()

Date              0
Voucher           0
Party             0
Product           0
Qty               0
Rate              0
Gross             0
Disc              0
Voucher Amount    0
dtype: int64

In [28]:
sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0,3380.0,0.0,13100.0
1,2017-04-01,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,13100.0
2,2017-04-01,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,11500.0,0.0,30990.0
3,2017-04-01,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,30990.0
4,2017-04-01,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0,8450.0,0.0,30990.0
...,...,...,...,...,...,...,...,...,...
111197,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140.0,26.0,3640.0,0.0,34980.0
111198,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600.0,8.4,5040.0,0.0,34980.0
111199,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0,5120.0,0.0,34980.0
111200,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800.0,8.5,6800.0,0.0,34980.0
111201,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0,6400.0,0.0,34980.0

In [30]:
sales_data.to_csv(r"C:\Users\gthangar\OneDrive - Nokia\1830_Automation\ML\Task\DataAnalysis\Sales_Data_Output.csv",index=False)